// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using System;
using System.Collections.Generic;
using Newtonsoft.Json;
using Newtonsoft.Json.Linq;
using JsonObj.XXT_BY.LoginJsonTypes;

namespace JsonObj.XXT_BY.LoginJsonTypes
{

    public class Function
    {

        [JsonProperty("funId")]
        public int FunId { get; set; }

        [JsonProperty("funKey")]
        public string FunKey { get; set; }

        [JsonProperty("funName")]
        public string FunName { get; set; }

        [JsonProperty("funType")]
        public int FunType { get; set; }
    }

    public class Role
    {

        [JsonProperty("functions")]
        public Function[] Functions { get; set; }

        [JsonProperty("roleId")]
        public int RoleId { get; set; }

        [JsonProperty("roleName")]
        public string RoleName { get; set; }
    }

    public class Role2
    {

        [JsonProperty("roleId")]
        public int RoleId { get; set; }

        [JsonProperty("roleName")]
        public string RoleName { get; set; }
    }

    public class School
    {

        [JsonProperty("currentWeek")]
        public int CurrentWeek { get; set; }

        [JsonProperty("schoolId")]
        public int SchoolId { get; set; }

        [JsonProperty("schoolName")]
        public string SchoolName { get; set; }

        [JsonProperty("weekTotal")]
        public int WeekTotal { get; set; }
    }

    public class Userinfo
    {

        [JsonProperty("clientAppId")]
        public string ClientAppId { get; set; }

        [JsonProperty("receiveNum")]
        public string ReceiveNum { get; set; }

        [JsonProperty("role")]
        public Role Role { get; set; }

        [JsonProperty("roles")]
        public Role2[] Roles { get; set; }

        [JsonProperty("school")]
        public School School { get; set; }

        [JsonProperty("score")]
        public int Score { get; set; }

        [JsonProperty("sex")]
        public int Sex { get; set; }

        [JsonProperty("userId")]
        public int UserId { get; set; }

        [JsonProperty("userName")]
        public string UserName { get; set; }
    }

    public class Teacher
    {

        [JsonProperty("sex")]
        public int Sex { get; set; }

        [JsonProperty("teacherID")]
        public int TeacherID { get; set; }

        [JsonProperty("teacherName")]
        public string TeacherName { get; set; }
    }

    public class Data
    {

        [JsonProperty("students")]
        public object Students { get; set; }

        [JsonProperty("classList")]
        public object ClassList { get; set; }

        [JsonProperty("userinfo")]
        public Userinfo Userinfo { get; set; }

        [JsonProperty("teacher")]
        public Teacher Teacher { get; set; }

        [JsonProperty("alltags")]
        public string[] Alltags { get; set; }
    }

}

namespace JsonObj.XXT_BY
{

    public class Login
    {

        [JsonProperty("code")]
        public string Code { get; set; }

        [JsonProperty("data")]
        public Data Data { get; set; }

        [JsonProperty("message")]
        public object Message { get; set; }
    }

}
